

SELECT Name, Salary, Gender, 
COUNT(Gender) OVER (PARTITION BY Gender) TotalGender,
Avg(Salary) OVER (PARTITION BY Gender) AvgSal,
MIN(Salary) OVER (PARTITION BY Gender) MinSal,
MAX(Salary) OVER (PARTITION BY Gender) MaxSal
FROM Employees

SELECT *, 
ROW_NUMBER() OVER (PARTITION BY Country ORDER BY Country) RowNum
FROM Employees

SELECT *, 
RANK() OVER(ORDER BY SALARY DESC) [Rank],
DENSE_RANK() OVER(ORDER BY SALARY DESC) [DensRank]
FROM Employees

SELECT *, 
RANK() OVER(PARTITION BY Gender ORDER BY SALARY DESC) [Rank],
DENSE_RANK() OVER(PARTITION BY Gender ORDER BY SALARY DESC) [DensRank]
FROM Employees

WITH EmpCte AS (
SELECT *, 
RANK() OVER(ORDER BY SALARY DESC) SalaryRank
FROM Employees
)
SELECT * FROM EmpCte WHERE SalaryRank=4

WITH EmpCte AS (
SELECT *, 
DENSE_RANK() OVER(ORDER BY SALARY DESC) SalaryRank
FROM Employees
)
SELECT * FROM EmpCte WHERE SalaryRank=4